[package]
name = "srv"
version = "0.1.0"
authors = ["Chris P <chrisp1877@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[[bin]]
name = "prod"
path = "src/bin/prod.rs"

[[bin]]
name = "dev"
path = "src/bin/dev.rs"

[dependencies]
api= {path="./api", optional=false}
db={path="./db/"}
com={path="./com/"}
log="*"

[features]
actix = ["api/actix"]
tide = ["api/tide"]
warp = ["api/warp"]

