[package]
name = "divapi"
version = "0.1.0"
authors = ["Chris P <chrisp1877@gmail.com>"]
edition = "2018"
default-run = "main"

[lib]
path = "src/lib.rs"

[[bin]]
name = "main"
path = "src/bin/main.rs"

[[bin]]
name = "gql"
path = "src/bin/gql.rs"
required-features= ["gql"]

[dependencies]
tokio = { version = "*", features = [ "full" ] }
serde = { version = "*", features = [ "derive" ] }
chrono = { version = "*", features= [ "serde" ] }
#validator = { version = "*", features = [ "derive" ] }
futures = "*"
serde_json = "*"
actix-service = "*"
actix = "*"
actix-rt = "*"
actix-web = "*"
actix-cors = "*"
actix-files = "*"
actix-identity = "*"
actix-session="*"
actix-web-actors = "3.0.0"
actix-multipart = "*"
derive_more = "*"
actix-redis = "*"
#oxide-auth="*"
#oxide-auth-actix="*"
reqwest = { version="*", features = ["json"] }
#jsonwebtoken = "*"
#actix-casbin-auth="*"

async-graphql = { version = "*", optional= true }
async-graphql-actix-web = { version = "*", optional = true }

rusoto_core = { version = "*", optional = true }
rusoto_cognito_idp = { version = "*", optional = true }
rusoto_cognito_identity = { version = "*", optional = true }

divdb = { path = "./db/" }
com = { path = "./com/" }

[dev-dependencies]
log = "*"
#listenfd = "*"
#dotenv="*"

[features]
default=[]
graphql=["divdb/gql", "async-graphql", "async-graphql-actix-web"]
cognito=["rusoto_core", "rusoto_cognito_identity", "rusoto_cognito_idp"]

[profile.release]
lto=true
codegen-units=1
#opt-level='z' #optimize for size
panic='abort'

[alias]
r = "run"
b = "build"
