version 3.8
services:
  api:
    build: .
    ports:
      - "7777:7777"
    volumes:
      - .:/app
      - ./data:/data
    depends_on:
      - redis
  redis:
    image: bitnami/redis:latest-alpine

volumes:

