version 3.8
services:
  api:
    build: .
    ports:
      - "7777:7777"
    volumes:
      - .:/app
      - ./data:/data
    depends_on:
      - redis
      - postgres
  redis:
    image: bitnami/redis:latest-alpine

  postgres:
    image: postgre/postgresql:latest-alpine
    depends_on: redis

  traefik:
    image: traefik/traefik:latest
    volumes:
      - ./data:./data
    depends_on: api

volumes:
  - postgres_volume:
      path:
        -

