[env]
DEV=true

[env.release]
DEV=false

[tasks.test]
command = "cargo"
args = [ "test" ]

[tasks.build]
command = "cargo"
args = [ "build", "--release" ]

[tasks.run]
command = "cargo"
args = [ "run", "--bin", "main" ]
