DROP TABLE Users CASCADE;
DROP TABLE UserInfo CASCADE;
DROP TABLE Items CASCADE;
DROP TABLE FactTypes CASCADE;
DROP TABLE FactEntries CASCADE;
DROP TABLE Records CASCADE;
DROP TABLE Groups CASCADE;

/*
DROP TABLE Fields CASCADE;
DROP TABLE ItemEntries CASCADE;
DROP TABLE FieldEntries CASCADE;
DROP TABLE GroupInfo CASCADE;
DROP TABLE Actions CASCADE;
DROP TABLE Rules CASCADE;
DROP TABLE Conditions CASCADE;

DROP TABLE GroupGroupLinks CASCADE;
DROP TABLE GroupUserLink CASCADE;
DROP TABLE GroupRecordLink CASCADE;
DROP TABLE UserUserLinks CASCADE;
DROP TABLE UserRecordLinks CASCADE;
DROP TABLE UserItemLinks CASCADE;
DROP TABLE RecordRecordLinks CASCADE;
DROP TABLE RecordItemLinks CASCADE;
DROP TABLE ItemItemLinks CASCADE;
DROP TABLE ItemFieldLinks CASCADE;
DROP TABLE FieldFieldLinks CASCADE;

DROP TABLE Tags CASCADE;
DROP TABLE ItemTags CASCADE;
DROP TABLE RecordItems CASCADE;
DROP TABLE FieldTags CASCADE;

DROP TABLE Relations;
*/
