CREATE TABLE IF NOT EXISTS Items (
    id UUID PRIMARY KEY NOT NULL,
    uid UUID NOT NULL REFERENCES Users(id),
    name TEXT NOT NULL CHECK (CHAR_LENGTH(name) < 80),
    status TEXT NOT NULL DEFAULT 'active',
    permission TEXT NOT NULL DEFAULT 'private',
    created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP
);
