---
- name: Deploy to io.div.is
  hosts: io.div.is
  remote_user: root
  vars:
    pg_user: user
    pg_pass: pass
    pg_db: db
    host_port: 80
    cont_port: 5005
  tasks:
    - name: Create app data dir
      file:
        path: /usr/src/div/data
        state: directory
    - name: Copy postgres files
      synchronize:
        src: ../data
        dest: /usr/src/div/data/
        mode: push
    - name: Copy back end files
      synchronize:
        src: ./
        dest: /usr/src/div/
        mode: push
        rsync_opts:
          - "--exclude=target:db/target:com/target:com/aws/target:com/aws/lambda/target"
    - name: Build backend bin
      command: cargo build --release
    - name: Install binary
      command: cargo install --path ./
    - name: Clean up source files
      command: cd ../ && rm -rf div
    - name: Run redis server
      command: redis-server
    - name: Run installed binary
      command: /usr/local/cargo/bin/divapi

