[package]
name = "api"
version = "0.1.0"
authors = ["Chris P <chrisp1877@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
path = "src/lib.rs"

[dependencies]
db = { path = "../db/" }
common = { path = "../common/" }

actix="*"
actix-rt="*"
actix-web="*"
actix-cors="*"
actix-session="*"
#actix-identity="*"
#actix-service="*"

serde_json = "*"
serde = { version = "*", features = [ "std", "derive" ] }
chrono= { version = "*", features = [ "serde", "clock", "std" ] }
uuid = { version = "*", features = [ "serde", "v4", "std" ] }
validator = { version = "0.11", features = [ "derive" ] }
rand="*"
#redis = { version = "0.16.0", default-features = false, features = ["tokio-rt-core"] }
#bcrypt="*"
#async-graphql = "=2.0.0-alpha.13"
#async-graphql-actix-web = "=2.0.0-alpha.13"
#futures="*"


[dev-dependencies]
log="*"
env_logger="*"
dotenv="*"

[[bin]]
name="main"
path="./src/bin/main.rs"

[[bin]]
name="dev"
path="./src/bin/dev.rs"

[[bin]]
name="prod"
path="./src/bin/prod.rs"
