[package]
name = "api"
version = "0.1.0"
authors = ["Chris P <chrisp1877@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
#actix-web
actix="*"
actix-rt="*"
actix-web="*"
actix-http="*"
chrono="*"
tokio={version="*", features=["full"]}
serde={version="*", features=["derive"]}
serde_json="*"

#[dev.dependencies]
#log="*"

#[lib]
#name = "dia_lib"
#path = "src/lib.rs"

#[[bin]]
#name = "dia_bin"
#path = "src/bin.rs"
